contentful/contentful.java

- src/main/java/com/contentful/java/cda/ResourceTypeAdapter.java
> Fix possible NPE for Asset de-serialization

- src/main/java/com/contentful/java/cda/ResourceTypeAdapter.java
- src/test/kotlin/com/contentful/java/cda/SerializationTests.kt
- src/test/resources/entry_no_fields.json
> Fix NPE when deserializing an entry with no fields

- .buildscript/deploy_snapshot.sh
- .buildscript/settings.xml
- .gitignore
- .travis.yml
- README.md
- pom.xml
> Auto-deploy snapshots to Sonatype

- src/main/java/com/contentful/java/cda/BaseModule.java
- src/main/java/com/contentful/java/cda/Constants.java
> Default to UTF-8 charset

- src/main/java/com/contentful/java/cda/ArrayUtil.java
- src/test/java/com/contentful/java/cda/LinkTest.java
- src/test/resources/links_unresolved.json
> Nullify unresolved links

- src/main/java/com/contentful/java/cda/AbsQuery.java
- src/main/java/com/contentful/java/cda/FetchQuery.java
- Set correct type for `FetchQuery`.
- Make `AbsQuery` package-local.
> Query fixes

- src/main/java/com/contentful/java/cda/Localization.java
- src/main/java/com/contentful/java/cda/LocalizedResource.java
- src/test/java/com/contentful/java/cda/EntryTest.java
- src/test/java/com/contentful/java/cda/SyncTest.java
> Make `getField()` fallback to default locale

- src/main/java/com/contentful/java/cda/ResourceUtils.java
- src/test/java/com/contentful/java/cda/LinkTest.java
- src/test/resources/links/sync_empty_links.json
> Fix NPE for null links

- CHANGELOG.md
- src/main/java/com/contentful/java/cda/ArrayResource.java
- src/main/java/com/contentful/java/cda/ResourceFactory.java
- src/main/java/com/contentful/java/cda/ResourceUtils.java
- src/test/java/com/contentful/java/cda/EntryTest.java
- src/test/java/com/contentful/java/cda/LinkTest.java
- src/test/resources/arrays/content_types.json
- src/test/resources/arrays/entries.json
- src/test/resources/arrays/space.json
> Remove linked resources from `CDAArray.items()`

- CHANGELOG.md
- src/main/java/com/contentful/java/cda/ResourceUtils.java
- src/test/java/com/contentful/java/cda/SyncTest.java
- src/test/resources/links_invalid/content_types.json
- src/test/resources/links_invalid/space.json
- src/test/resources/links_invalid/sync_initial.json
> Fix CME for invalid links on multiple locales field

- src/main/java/com/contentful/java/cda/CDAArray.java
- src/main/java/com/contentful/java/cda/CDAAsset.java
- src/main/java/com/contentful/java/cda/CDAClient.java
- src/main/java/com/contentful/java/cda/CDAContentType.java
- src/main/java/com/contentful/java/cda/CDAEntry.java
- src/main/java/com/contentful/java/cda/CDAField.java
- src/main/java/com/contentful/java/cda/CDALocale.java
- src/main/java/com/contentful/java/cda/CDASpace.java
- src/main/java/com/contentful/java/cda/DeletedResource.java
- src/main/java/com/contentful/java/cda/FetchQuery.java
- src/main/java/com/contentful/java/cda/ObserveQuery.java
- src/main/java/com/contentful/java/cda/SyncQuery.java
- src/main/java/com/contentful/java/cda/SynchronizedSpace.java
Removing final from accessable classes, makes them easier to be
tested.
> Removing final from public classes

- CHANGELOG.md
- README.md
- src/main/java/com/contentful/java/cda/CDAClient.java
- src/test/java/com/contentful/java/cda/BaseTest.java
- src/test/java/com/contentful/java/cda/SyncTest.java
- src/test/resources/links_invalid/preview_space.json
Before it was possible to call the preview endpoint for syncing, but
parsing the result threw an exception, since the structure between
the response differs.
Please use the production environment for syncing.
> Throwing OperationNotSupportedException if trying to sync in preview

- CHANGELOG.md
- src/main/java/com/contentful/java/cda/CDAArray.java
- src/main/java/com/contentful/java/cda/CDAClient.java
- src/main/java/com/contentful/java/cda/CDALocale.java
- src/main/java/com/contentful/java/cda/CDAResource.java
- src/main/java/com/contentful/java/cda/ResourceDeserializer.java
- src/main/java/com/contentful/java/cda/ResourceUtils.java
- src/main/java/com/contentful/java/cda/Util.java
- src/main/java/com/contentful/java/cda/interceptor/AuthorizationHeaderInterceptor.java
- src/main/java/com/contentful/java/cda/interceptor/UserAgentHeaderInterceptor.java
- src/test/java/com/contentful/java/cda/AssetTest.java
- src/test/java/com/contentful/java/cda/BaseTest.java
- src/test/java/com/contentful/java/cda/CallbackTest.java
- src/test/java/com/contentful/java/cda/ClientTest.java
- src/test/java/com/contentful/java/cda/ContentTypeTest.java
- src/test/java/com/contentful/java/cda/EntryTest.java
- src/test/java/com/contentful/java/cda/LinkTest.java
- src/test/java/com/contentful/java/cda/SpaceTest.java
- src/test/java/com/contentful/java/cda/SyncTest.java
- src/test/java/com/contentful/java/cda/lib/EnqueueResponseRule.java
- src/test/java/com/contentful/java/cda/lib/TestCallback.java
use OkHttp3 Call.Factory interface for customization, idea is based on PR https://github.com/contentful/contentful.java/pull/116
> Reintroduce customization of http client

- src/main/java/com/contentful/java/cda/CDAField.java
- src/test/java/com/contentful/java/cda/ContentTypeTest.java
- src/test/java/com/contentful/java/cda/integration/Integration.java
- src/test/resources/demo/content_types_cat.json
Addresses https://github.com/contentful/contentful.java/issues/124
Just fixes de-serialisation. Does not evaluate the validations.
> Add support for CDAField validations

- .buildscript/integration_tests.sh
- .travis.yml
start communicating with our end to end testing infrastructure, every time this SDK gets build.
> Integrate end to end tests

- CHANGELOG.md
- README.md
- src/main/java/com/contentful/java/cda/AbsQuery.java
- src/main/java/com/contentful/java/cda/QueryOperation.java
- src/main/java/com/contentful/java/cda/Util.java
- src/test/java/com/contentful/java/cda/AbsQueryTest.java
- src/test/java/com/contentful/java/cda/integration/Integration.java
With this PR, we enable searching easier for entries in Contenful. Additionally we added the `select` feature from the API.
> Improve search query support

- CHANGELOG.md
- README.md
- src/main/java/com/contentful/java/cda/CDAAsset.java
- src/main/java/com/contentful/java/cda/CDAClient.java
- src/main/java/com/contentful/java/cda/image/ImageOption.java
- src/main/java/com/contentful/java/cda/interceptor/AuthorizationHeaderInterceptor.java
- src/main/java/com/contentful/java/cda/interceptor/ContentfulUserAgentHeaderInterceptor.java
- src/main/java/com/contentful/java/cda/interceptor/HeaderInterceptor.java
- src/main/java/com/contentful/java/cda/interceptor/UserAgentHeaderInterceptor.java
- src/test/java/com/contentful/java/cda/AssetTest.java
- src/test/java/com/contentful/java/cda/ClientTest.java
- src/test/java/com/contentful/java/cda/interceptor/ContentfulUserAgentHeaderInterceptorTest.java
- src/test/resources/demo/assets_no_image.json
Now you can use all the neat features of the image api, without the need of remebering the parameters of the url, just use `.urlForImageWith(…)` method on assets.
> Add image API

- CHANGELOG.md
- src/main/java/com/contentful/java/cda/interceptor/ContentfulUserAgentHeaderInterceptor.java
- src/test/java/com/contentful/java/cda/ClientTest.java
- src/test/java/com/contentful/java/cda/interceptor/ContentfulUserAgentHeaderInterceptorTest.java
⚫Ignore non ASCII characters in names 
⚫Do not add versions with non Arabic letters.
> Do not send non ASCII characters in custom HTTP header

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/contentful/java/cda/AbsQuery.java
- src/test/java/com/contentful/java/cda/AbsQueryTest.java
- src/test/java/com/contentful/java/cda/integration/Integration.java
- added new query methods `linksToEntryId`, `linksToEntry`, `linksToAssetId`, `linksToAsset`
- added tests
> added support for incoming-links

- src/main/java/com/contentful/java/cda/CDAClient.java
- src/main/java/com/contentful/java/cda/CDAService.java
- src/main/java/com/contentful/java/cda/ResourceUtils.java
- src/main/java/com/contentful/java/cda/SyncQuery.java
- src/main/java/com/contentful/java/cda/SyncType.java
- src/test/java/com/contentful/java/cda/ClientTest.java
- src/test/java/com/contentful/java/cda/SyncTest.java
- src/test/java/com/contentful/java/cda/SyncTypeTest.java
- src/test/java/com/contentful/java/cda/integration/Integration.java
add feature for syncing only parts of the content.
Great shout out to @vbondarovich for the contribution.
> feature: sync additional params

- CHANGELOG.md
- pom.xml
- src/main/java/com/contentful/java/cda/interceptor/ContentfulUserAgentHeaderInterceptor.java
- src/test/java/com/contentful/java/cda/interceptor/ContentfulUserAgentHeaderInterceptorTest.java
> fix: remove localisation to non English (ASCII) characters

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/contentful/java/cda/AbsQuery.java
- src/main/java/com/contentful/java/cda/CDACallback.java
- src/main/java/com/contentful/java/cda/CDAClient.java
- src/main/java/com/contentful/java/cda/Callbacks.java
- src/main/java/com/contentful/java/cda/TransformQuery.java
- src/main/java/com/contentful/java/cda/Util.java
- src/test/java/com/contentful/java/cda/TransformedEntriesTest.java
- src/test/java/com/contentful/java/cda/integration/Integration.java
This feature is up to debate and Contentful is looking for feedback on it.
> add beta feature: unwrapping of CDAEntries

- CHANGELOG.md
- README.md
- src/main/java/com/contentful/java/cda/CDAClient.java
- src/main/java/com/contentful/java/cda/CDAHttpException.java
- src/main/java/com/contentful/java/cda/CDAService.java
- src/main/java/com/contentful/java/cda/ObserveQuery.java
- src/main/java/com/contentful/java/cda/ResourceFactory.java
- src/main/java/com/contentful/java/cda/ResourceUtils.java
- src/main/java/com/contentful/java/cda/SyncQuery.java
- src/main/java/com/contentful/java/cda/TlsSocketFactory.java
- src/main/java/com/contentful/java/cda/TransformQuery.java
- src/main/java/com/contentful/java/cda/Util.java
- src/main/java/com/contentful/java/cda/interceptor/LogInterceptor.java
- src/main/java/com/contentful/java/cda/rich/RichTextFactory.java
- src/test/java/com/contentful/java/cda/LocaleFallbackTest.java
This fix is related to almost outdated versions of android: L and M are not bundling `java.util.function.*` classes. So this change will introduce workaround for those.
> Fix: Don't use java.util.function.*

- .buildscript/codecov.sh
- .codecov.yml
- CHANGELOG.md
- src/main/java/com/contentful/java/cda/rich/RichTextFactory.java
- src/test/bash/rich_text-sync_continued.sh
- src/test/bash/rich_text-sync_initial.sh
- src/test/java/com/contentful/java/cda/RichTextTest.java
- src/test/resources/rich_text/sync_continued.json
- src/test/resources/rich_text/sync_initial.json
> fix: do not parse rich text if it is already parsed

- src/main/java/com/contentful/java/cda/AbsQuery.java
- src/test/java/com/contentful/java/cda/AbsQueryTest.java
- src/test/java/com/contentful/java/cda/integration/Integration.java
Fixes #195
Extends AbsQuery by additional "withLocale" method.
> AbsQuery has been extended by "withLocale" method

- checkstyle.xml
- pom.xml
As a result of automated audit we needed to update the checkstyle plugin version. This needed some alignments in the checkstyle.xml configuration also.
> Update checkstyle plugin version, fix checkstyle.xml issues

- pom.xml
- src/main/java/com/contentful/java/cda/ArrayResource.java
- src/main/java/com/contentful/java/cda/CDAArray.java
- src/main/java/com/contentful/java/cda/CDAAsset.java
- src/main/java/com/contentful/java/cda/CDAClient.java
- src/main/java/com/contentful/java/cda/CDAContentType.java
- src/main/java/com/contentful/java/cda/CDAEntry.java
- src/main/java/com/contentful/java/cda/CDAError.java
- src/main/java/com/contentful/java/cda/CDAField.java
- src/main/java/com/contentful/java/cda/CDALocale.java
- src/main/java/com/contentful/java/cda/CDAResource.java
- src/main/java/com/contentful/java/cda/CDASpace.java
- src/main/java/com/contentful/java/cda/DeletedResource.java
- src/main/java/com/contentful/java/cda/LocalizedResource.java
- src/main/java/com/contentful/java/cda/NestedTypeDeserializer.java
- src/main/java/com/contentful/java/cda/NestedTypeResolver.java
- src/main/java/com/contentful/java/cda/ResourceFactory.java
- src/main/java/com/contentful/java/cda/SynchronizedSpace.java
- src/main/java/com/contentful/java/cda/Util.java
- src/main/resources/logback.xml
- src/test/java/com/contentful/java/cda/ClientTest.java
- src/test/java/com/contentful/java/cda/EntryTest.java
- src/test/java/com/contentful/java/cda/LocaleTest.java
- src/test/java/com/contentful/java/cda/integration/Integration.java
- src/test/java/com/contentful/java/cda/integration/IntegrationWithMasterEnvironment.java
I would like to use `jackson` instead of `gson` for converter factory . This pr makes it possible.
#219
> feat: custom converter factory

- src/main/java/com/contentful/java/cda/rich/RichTextFactory.java
This fixes issue in the [https://github.com/contentful/contentful.java/issues/265](https://github.com/contentful/contentful.java/issues/265)
> fix: Properly resolve embedded inline entry in RTE tables.

- src/main/java/com/contentful/java/cda/image/ImageOption.java
- src/main/java/com/contentful/java/cda/rich/RichTextFactory.java
Add support for avif format. 
Add support for parsing rich text from JSON.
> feat: Add support for avif format and parsing rich text document from JSON.

- README.md
- pom.xml
- src/main/java/com/contentful/java/cda/CDAHttpException.java
This should fix issue reported here: https://github.com/contentful/contentful.java/issues/304
> fix: Logging sensitive data headers

- CHANGELOG.md
- README.md
- pom.xml
- src/main/java/com/contentful/java/cda/CDAClient.java
- src/main/java/com/contentful/java/cda/CDAService.java
- src/main/java/com/contentful/java/cda/ResourceUtils.java
- src/main/java/com/contentful/java/cda/SyncQuery.java
- src/test/java/com/contentful/java/cda/SyncTest.java
This will add `limit` query param to the Sync API call.
> feat: Add limit to Sync api call
